const wikiData = {
  heroes: [
    { original: "Abrams", translated: "エイブラムス", image: "", description: "", abilities: [{ name: "Siphon Life", desc: "(CD: 40秒) - 毎秒ダメージ: 35+0.2SP 【T1】CD-20秒 / 【T2】効果時間+2秒 / 【T3】毎秒ダメージ+40" }, { name: "Shoulder Charge", desc: "(CD: 35秒) - ダメージ: 40+2.1SP、スタン: 1秒 【T1】CD-20秒 / 【T2】効果時間+0.5秒 / 【T3】敵衝突後8秒間武器ダメージ+5.5" }, { name: "Infernal Resilience", desc: "(パッシブ) - 16秒でダメージの17%回復 【T1】体力自動回復+1.5 / 【T2】体力+150 / 【T3】回復割合+9%" }, { name: "Seismic Impact", desc: "(CD: 150秒) - ダメージ: 150+0.9SP 【T1】CD-40秒 / 【T2】25秒間、命中数×体力100＆連射速度+15% / 【T3】着地後3秒間状態異常無効化" }] },
    { original: "Apollo", translated: "アポロ", image: "", description: "", abilities: [{ name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }] },
    { original: "Bebop", translated: "ビバップ", image: "", description: "", abilities: [{ name: "Exploding Uppercut", desc: "(CD: 20秒) - 範囲ダメージ: 80+0.5SP 【T1】CD-11秒 / 【T2】命中時12秒間射程2倍・武器ダメ+60% / 【T3】命中時HookのCD解消＆弾数+100%" }, { name: "Sticky Bomb", desc: "(CD: 18秒) - ダメージ: 120+0.9SP 【T1】CD-8秒 / 【T2】ダメージ+80 / 【T3】爆弾が付いた敵を3.5秒武装解除" }, { name: "Hook", desc: "(CD: 22秒) - ダメージ: 40 【T1】対象へのバレットダメ10秒間+30% / 【T2】射程+30m / 【T3】CD-12秒" }, { name: "Hyper Beam", desc: "(CD: 110秒) - ダメージ: 220+3SP 【T1】CD-40秒 / 【T2】ダメージ+100 / 【T3】ヒーローへの与ダメージ100%分を回復" }] },
    { original: "Billy", translated: "ビリー", image: "", description: "", abilities: [{ name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }] },
    { original: "Calico", translated: "キャリコ", image: "", description: "", abilities: [{ name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }] },
    { original: "Celeste", translated: "セレステ", image: "", description: "", abilities: [{ name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }] },
    { original: "Dynamo", translated: "ダイナモ", image: "", description: "", abilities: [{ name: "Kinetic Pulse", desc: "(CD: 25秒) - ダメージ: 100+1.4SP 【T1】命中敵が4秒間40%スロウ / 【T2】命中敵への武器ダメ8秒間30%増 / 【T3】ダメージ+125" }, { name: "Quantum Entanglement", desc: "(CD: 11秒) - リロード＆連射速度25%増 【T1】射程+4m / 【T2】連射速度増加量+25% / 【T3】再出現時弾数+120%" }, { name: "Rejuvenating Aurora", desc: "(CD: 45秒) - 毎秒回復: 32+0.5SP 【T1】最大詠唱時8秒間移動+4m/s / 【T2】CD-15秒 / 【T3】使用中移動可＆最大体力4%毎秒回復" }, { name: "Singularity", desc: "(CD: 180秒) - 毎秒ダメージ: 60+0.2SP 【T1】範囲+2m / 【T2】詠唱時間+0.75秒 / 【T3】敵の最大体力3.8%のダメージを毎秒追加" }] },
    { original: "Doorman", translated: "ドアマン", image: "", description: "", abilities: [{ name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }] },
    { original: "Drifter", translated: "ドリフター", image: "", description: "", abilities: [{ name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }] },
    { original: "Grey Talon", translated: "グレイタロン", image: "", description: "", abilities: [{ name: "Charged Shot", desc: "(CD: 16秒) - ダメージ: 105+1.6SP" }] },
    { original: "Graves", translated: "グレイブス", image: "", description: "", abilities: [{ name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }] },
    { original: "Haze", translated: "ヘイズ", image: "", description: "", abilities: [{ name: "Sleep Dagger", desc: "(CD: 27秒) - ダメージ: 70+2.8SP、睡眠: 3秒 【T1】対象のスタミナ-1 / 【T2】CD-13秒 / 【T3】起床後6秒間バレットレジスト-12%" }, { name: "Smoke Bomb", desc: "(CD: 35秒) - スプリント速度: +2m/s 【T1】CD-15秒 / 【T2】スプリント速度+6m/s / 【T3】インビジ後8秒間+30%バレットライフスティール" }, { name: "Fixation", desc: "(パッシブ) - 命中ごと武器ダメ+0.2" }] },
    { original: "Holiday", translated: "ホリデイ", image: "", description: "", abilities: [{ name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }] },
    { original: "Infernus", translated: "インファーナス", image: "", description: "", abilities: [{ name: "Catalyst", desc: "(CD: 24秒) - ダメージ: 50+0.3SP、ダメージ増幅: 30% 【T1】チャージ数+1 / 【T2】20%ライフスティール獲得 / 【T3】ダメージ増幅+10%＆回復阻害-40%" }] },
    { original: "Ivy", translated: "アイビー", image: "", description: "", abilities: [{ name: "Kudzu Bomb", desc: "(CD: 30秒) - 毎秒ダメージ: 60+0.6SP 【T1】チャージ数+1 / 【T2】効果時間+2秒 / 【T3】毎秒ダメージ+60" }, { name: "Watcher's Covenant", desc: "(CD: 35秒) - 連射増加: 10%+0.2SP 【T1】連射増加+10% / 【T2】移動速度増加+3m/s / 【T3】接続人数+1" }, { name: "Stone Form", desc: "(CD: 40秒) - ダメージ: 80+1SP、回復: 最大体力の10% 【T1】CD-20秒 / 【T2】ダメージ+80＆スタン時間+0.5秒 / 【T3】回復量の最大体力割合+20%" }, { name: "Air Drop", desc: "(CD: 80秒) - 爆発ダメージ: 150+2.5SP、シールド: 200+2.5SP 【T1】命中敵のバレットレジスト12秒間-20% / 【T2】シールド+300＆爆発範囲+5m / 【T3】4.5秒のサイレンス付与" }] },
    { original: "Kelvin", translated: "ケルビン", image: "", description: "", abilities: [{ name: "Frost Grenade", desc: "(CD: 21秒) - ダメージ: 80+1SP 【T1】チャージ数+1 / 【T2】命中した味方を135+2SP回復 / 【T3】ダメージ+175" }, { name: "Ice Path", desc: "(CD: 36秒) - 移動・スプリント: +2m/s" }] },
    { original: "Lady Geist", translated: "レディガイスト", image: "", description: "", abilities: [{ name: "Essence Bomb", desc: "(CD: 10秒) - ダメージ: 100+1SP" }] },
    { original: "Lash", translated: "ラッシュ", image: "", description: "", abilities: [{ name: "Ground Strike", desc: "(CD: 18秒) - ダメージ: 90+0.8SP 【T1】CD-10秒 / 【T2】打ち上げ＆3秒間50%スロウ / 【T3】ダメ増加+110%＆SPスケール増" }, { name: "Grapple", desc: "(CD: 40秒) - ジャンプ移動 【T1】CD-20秒 / 【T2】射程+20m＆使用時10秒間武器ダメ+6 / 【T3】連射速度+20%" }, { name: "Flog", desc: "(CD: 25秒) - ダメージ: 65+1.2SP 【T1】3秒間35%スロウ / 【T2】CD-15秒 / 【T3】ダメージ+105＆35%連射スロウ" }, { name: "Death Slam", desc: "(CD: 130秒) - ダメージ: 115+1SP 【T1】投げ飛ばし最大距離+8m / 【T2】ダメージ+100 / 【T3】CD-60秒" }] },
    { original: "McGinnis", translated: "マクギニス", image: "", description: "", abilities: [{ name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }] },
    { original: "Mina", translated: "ミナ", image: "", description: "", abilities: [{ name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }] },
    { original: "Mirage", translated: "ミラージュ", image: "", description: "", abilities: [{ name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }] },
    { original: "Mo & Krill", translated: "モー＆クリル", image: "", description: "", abilities: [{ name: "Scorn", desc: "(CD: 12秒) - ダメージ: 60+0.4SP" }] },
    { original: "Page", translated: "ペイジ", image: "", description: "", abilities: [{ name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }] },
    { original: "Paradox", translated: "パラドックス", image: "", description: "", abilities: [{ name: "Pulse Grenade", desc: "(CD: 26秒) - 波動ダメージ: 45+0.5SP 【T1】波動回数+1 / 【T2】CD-8秒 / 【T3】波動ダメージ+45" }, { name: "Time Wall", desc: "(CD: 35秒) - 割合ダメージ: 10% 【T1】壁の幅+2m・高さ+1m / 【T2】チャージ数+1 / 【T3】触れた敵に3秒サイレンス" }, { name: "Kinetic Carbine", desc: "(CD: 28秒) - 増加移動速度: 25%+0.1SP 【T1】停止時間+0.5秒 / 【T2】CD-10秒＆移動増加時間+2秒 / 【T3】最大ダメージ増幅+50%" }, { name: "Paradoxical Swap", desc: "(CD: 45秒) - ダメージ: 125+0.7SP 【T1】射程+15m / 【T2】ダメージ+100 / 【T3】CD-15秒" }] },
    { original: "Pocket", translated: "ポケット", image: "", description: "", abilities: [{ name: "Barrage", desc: "(CD: 30秒) - 弾ダメ: 35+0.4SP、スタック増幅: 8% (パッチで6%)" }] },
    { original: "Rem", translated: "レム", image: "", description: "", abilities: [{ name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }] },
    { original: "Seven", translated: "セブン", image: "", description: "", abilities: [{ name: "Lightning Ball", desc: "(CD: 22秒) - 毎秒ダメージ: 80+0.5SP 【T1】チャージ数+1 / 【T2】40%スロウ / 【T3】毎秒ダメージ+70" }, { name: "Static Charge", desc: "(CD: 40秒) - ダメージ: 40+0.9SP 【T1】CD-20秒 / 【T2】範囲+7m / 【T3】スタン時間+1.1秒" }, { name: "Power Surge", desc: "(CD: 45秒) - 電撃ダメージ: 10+0.2SP 【T1】スピリットレジスト-15% / 【T2】CD-16秒 / 【T3】電撃ダメ+12＆連鎖+3" }, { name: "Storm Cloud", desc: "(CD: 180秒) - 毎秒ダメージ: 124+1.1SP 【T1】詠唱中バレットレジスト+35% / 【T2】詠唱+7秒＆範囲+10m / 【T3】毎秒ダメージ+75" }] },
    { original: "Shiv", translated: "シヴ", image: "", description: "", abilities: [{ name: "Serrated Knives", desc: "(CD: 18秒) - ダメージ: 35+0.6SP、出血ダメ: 5+0.2SP 【T1】チャージ数+1 / 【T2】効果時間+2秒 / 【T3】ダメ+40＆出血+5" }, { name: "Slice and Dice", desc: "(CD: 15秒) - ダメージ: 125+1.2SP" }] },
    { original: "Silver", translated: "シルバー", image: "", description: "", abilities: [{ name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }] },
    { original: "Sinclair", translated: "シンクレア", image: "", description: "", abilities: [{ name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }] },
    { original: "Venator", translated: "ヴェナトル", image: "", description: "", abilities: [{ name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }] },
    { original: "Victor", translated: "ビクター", image: "", description: "", abilities: [{ name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }] },
    { original: "Vindicta", translated: "ヴィンディクタ", image: "", description: "", abilities: [{ name: "Stake", desc: "(CD: 40秒) - ダメージ: 60+0.4SP、束縛: 2.25秒 【T1】束縛時間+0.75秒 / 【T2】CD-20秒 / 【T3】束縛敵にディザーム付与" }, { name: "Flight", desc: "(CD: 40秒) - 追加スピリットダメ: 10+0.2SP/発 【T1】飛行中弾数+50% / 【T2】CD-15秒 / 【T3】1発ダメ+12" }, { name: "Crow Familiar", desc: "(CD: 28秒) - ダメージ: 50+1SP、出血ダメ: 毎秒3% 【T1】カラスが2回跳ね返る / 【T2】CD-17秒 / 【T3】出血+3%＆阻害-40%" }, { name: "Assassinate", desc: "(CD: 50秒) - ダメージ: 160+1SP、追加ダメ: 145+1.6SP 【T1】CD-20秒 / 【T2】追加ダメ+140 / 【T3】追加ソウル+600" }] },
    { original: "Viper", translated: "ヴァイパー", image: "", description: "", abilities: [{ name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }, { name: "", desc: "" }] },
    { original: "Viscous", translated: "ヴィスカス", image: "", description: "", abilities: [{ name: "Splatter", desc: "(CD: 20秒) - ダメージ: 110+1.4SP 【T1】CD-6秒 / 【T2】ダメージ+70＆範囲+1m / 【T3】球が2回跳ねる" }, { name: "The Cube", desc: "(CD: 45秒) - 体力自動回復: +40 【T1】脱出後移動・スタミナ増 / 【T2】CD-22秒 / 【T3】自動回復+60" }, { name: "Puddle Punch", desc: "(CD: 24秒) - ダメージは自身の弱近接に依存 【T1】チャージ数+1 / 【T2】CD-10秒 / 【T3】ダメージ+80＆スロウ+20%" }, { name: "Goo Ball", desc: "(CD: 90秒) - ダメージ: 140+1SP 【T1】効果時間+5秒 / 【T2】ダメージ+120 / 【T3】ボール状態でもスキル・アイテム使用可" }] },
    { original: "Warden", translated: "ウォーデン", image: "", description: "", abilities: [{ name: "Alchemical Flask", desc: "(CD: 13秒) - ダメージ: 55+0.8SP、武器ダメ減: -30% 【T1】ダメージ+40 / 【T2】スタミナ減少+1 / 【T3】CD-7秒＆連射スロウ+35%" }, { name: "Willpower", desc: "(CD: 40秒) - シールド: 150、移動速度: +15% 【T1】移動速度+20% / 【T2】CD-20秒 / 【T3】シールド+200＆3.9SPスケール追加" }, { name: "Binding Word", desc: "(CD: 35秒) - ダメージ: 120+2.6SP、移動不能: 1.75秒 【T1】移動不能時間+1秒 / 【T2】CD-20秒 / 【T3】捕獲した敵へのバレットダメ20%増" }, { name: "Last Stand", desc: "(CD: 130秒) - 毎秒ダメージ: 100+0.9SP 【T1】範囲+3m / 【T2】毎秒ダメ+70 / 【T3】CD-60秒" }] },
    { original: "Wraith", translated: "レイス", image: "", description: "", abilities: [{ name: "Card Trick", desc: "(CD: 0.5秒) - ダメージ: 100+1.2SP 【T1】チャージ数+1 / 【T2】ダメージ+50 / 【T3】召喚効率+50%" }, { name: "Project Mind", desc: "(CD: 45秒) - 指定地点テレポート 【T1】射程+15m / 【T2】バレットシールド獲得 / 【T3】CD-30秒" }, { name: "Full Auto", desc: "(CD: 45秒) - 連射速度増加: +20% 【T1】CD-15秒 / 【T2】1発ごとに5+0.1SPダメ / 【T3】+35%バレットライフスティール" }, { name: "Telekinesis", desc: "(CD: 90秒) - ダメージ: 200+1SP 【T1】CD-30秒 / 【T2】効果時間+0.5秒 / 【T3】対象が周囲の全敵になる" }] },
    { original: "Yamato", translated: "ヤマト", image: "", description: "", abilities: [{ name: "Power Slash", desc: "(CD: 8秒) - 最大ダメージ: 170+2SP 【T1】詠唱中+60バレットレジスト / 【T2】3秒間40%スロウ / 【T3】最大ダメージ+200" }, { name: "Flying Strike", desc: "(CD: 20秒) - ダメージ: 70+0.7SP 【T1】スロウ効果+25% / 【T2】射程+20m / 【T3】命中後10秒間武器ダメ+6" }, { name: "Crimson Slash", desc: "(CD: 11秒) - ダメージ: 60+0.4SP、回復: 70+1.1SP 【T1】連射スロウ+30% / 【T2】回復量最大体力の10%増 / 【T3】CD-6秒" }, { name: "Shadow Transformation", desc: "(CD: 100秒) - 変化中無敵、スキル速度+60% 【T1】CD-30秒 / 【T2】移動速度+4m/s / 【T3】効果時間+1.5秒" }] }
  ],
  items: {
    weapon: [
      { original: "Close Quarters", translated: "クローズクォーター", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Basic Magazine", translated: "基礎拡張マガジン", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Headshot Booster", translated: "ヘッドショットブースター", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "High-Velocity Rounds", translated: "ハイスピードラウンド", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Monster Rounds", translated: "モンスターラウンド", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Rapid Rounds", translated: "ラピッドラウンド", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Restorative Shot", translated: "ヒーリングショット", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Active Reload", translated: "アクティブリロード", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Fleetfoot", translated: "フリートフット", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Intensifying Magazine", translated: "連射強化マガジン", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Kinetic Dash", translated: "キネティックダッシュ", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Long Range", translated: "ロングレンジ", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Melee Charge", translated: "メレーチャージ", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Mystic Shot", translated: "ミスティックショット", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Opening Rounds", translated: "オープニングラウンド", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Recharging Rush", translated: "リチャージラッシュ", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Slowing Bullets", translated: "スロウバレット", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Spirit Shredder", translated: "スピリットシュレッダー", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Split Shot", translated: "スプリットショット", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Stalker", translated: "ストーカー", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Swift Striker", translated: "スイフトストライカー", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Titanic Magazine", translated: "巨大拡張マガジン", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Weakening Headshot", translated: "イグゾーストヘッドショット", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Alchemical Fire", translated: "アルケミカルファイア", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Ballistic Enchantment", translated: "バリスティックエンチャント", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Berserker", translated: "バーサーカー", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Blood Tribute", translated: "ブラッドトリビュート", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Burst Fire", translated: "バーストファイア", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Sacrifice", translated: "サクリファイス", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Escalating Resilience", translated: "エスカレートレジリエンス", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Express Shot", translated: "エクスプレスショット", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Headhunter", translated: "ヘッドハンター", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Heroic Aura", translated: "ヒロイックオーラ", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Hollow Point", translated: "ホロウポイント", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Hunter's Aura", translated: "ハンターオーラ", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Point Blank", translated: "ポイントブランク", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Sharpshooter", translated: "シャープシューター", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Spirit Rend", translated: "スピリットキラー", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Tesla Bullets", translated: "テスラバレット", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Toxic Bullets", translated: "トキシックバレット", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Weighted Shots", translated: "ヘヴィショット", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Armor Piercing Rounds", translated: "アーマーピアッサー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Capacitor", translated: "コンデンサー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Crippling Headshot", translated: "クリップリングショット", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Crushing Fists", translated: "クラッシュフィスト", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Frenzy", translated: "フレンジー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Glass Cannon", translated: "グラスキャノン", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Lucky Shot", translated: "ラッキーショット", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Ricochet", translated: "リコシェ", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Shadow Weave", translated: "シャドウウィーブ", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Silencer", translated: "サイレンサー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Spellslinger", translated: "スペルスリンガー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Spiritual Overflow", translated: "スピリットオーバーフロー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Haunting Shot", translated: "ホーンテッドショット", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Infinite Rounds", translated: "インフィニットラウンド", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Runed Gauntlets", translated: "ルーンガントレット", image: "", price: "Legendary", duration: "", effects: [], description: "" }
    ],
    vitality: [
      { original: "Extra Health", translated: "エクストラヘルス", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Extra Regen", translated: "エクストラリジェネ", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Extra Stamina", translated: "エクストラスタミナ", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Healing Rite", translated: "ヒーリングリチュアル", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Melee Lifesteal", translated: "メレーライフスティール", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Rebuttal", translated: "プロテスト", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Sprint Boots", translated: "スプリントブーツ", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Battle Vest", translated: "バトルベスト", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Bullet Lifesteal", translated: "バレットライフスティール", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Debuff Reducer", translated: "デバフリデューサー", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Enchanter's Emblem", translated: "妖術師の紋章", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Enduring Speed", translated: "ウィングブーツ", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Guardian Ward", translated: "ガーディアンワード", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Healbane", translated: "ヒールベイン", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Healing Booster", translated: "ヒーリングブースター", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Reactive Barrier", translated: "リアクティブバリア", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Restorative Locket", translated: "ヒーリングロケット", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Return Fire", translated: "リターンファイア", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Spirit Lifesteal", translated: "スピリットライフスティール", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Spirit Shielding", translated: "スピリットシールド", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Weapon Shielding", translated: "ウェポンシールド", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Bullet Resilience", translated: "バレットレジリエンス", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Counterspell", translated: "カウンタースペル", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Dispel Magic", translated: "ディスペルマジック", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Fortitude", translated: "フォルティチュード", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Fury Trance", translated: "フューリートランス", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Healing Nova", translated: "ヒーリングノヴァ", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Lifestrike", translated: "ライフストライク", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Majestic Leap", translated: "マジェスティックリープ", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Metal Skin", translated: "メタルスキン", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Rescue Beam", translated: "レスキュービーム", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Spirit Resilience", translated: "スピリットレジリエンス", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Stamina Mastery", translated: "スタミナマスタリー", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Trophy Collector", translated: "トロフィーコレクター", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Veil Walker", translated: "ベールウォーカー", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Warp Stone", translated: "ワープストーン", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Cheat Death", translated: "デスチーター", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Colossus", translated: "コロッサス", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Divine Barrier", translated: "ディバインバリア", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Diviner's Kevlar", translated: "ディバイナーズケブラー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Healing Tempo", translated: "ヒーリングテンポ", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Infuser", translated: "インフューザー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Inhibitor", translated: "インヒビター", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Juggernaut", translated: "ジャガーノート", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Leech", translated: "ライフドレイン", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Phantom Strike", translated: "ファントムストライク", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Plated Armor", translated: "プレートアーマー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Siphon Bullets", translated: "サイフォンバレット", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Spellbreaker", translated: "スペルブレイカー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Unstoppable", translated: "アンストッパブル", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Vampiric Burst", translated: "ヴァンパイアバースト", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Witchmail", translated: "ウィッチメイル", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Celestial Blessing", translated: "天の祝福", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Cloak of Opportunity", translated: "加護のマント", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Electric Slippers", translated: "エレクトリックブーツ", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Eternal Gift", translated: "エターナルギフト", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Nullification Burst", translated: "虚無の波動", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Seraphim Wings", translated: "セラフィムウィング", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Shadow Strike", translated: "シャドウストライク", image: "", price: "Legendary", duration: "", effects: [], description: "" }
    ],
    spirit: [
      { original: "Extra Charge", translated: "エクストラチャージ", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Extra Spirit", translated: "エクストラスピリット", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Golden Goose Egg", translated: "ガチョウの黄金の卵", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Mystic Burst", translated: "ミスティックバースト", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Mystic Expansion", translated: "ミスティックエクスパンダー", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Mystic Regeneration", translated: "ミスティックリジェネ", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Rusted Barrel", translated: "コロッシブバレル", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Spirit Strike", translated: "スピリットストライク", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Arcane Surge", translated: "アーケインサージ", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Bullet Resist Shredder", translated: "レジストシュレッダー", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Cold Front", translated: "コールドフロント", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Compress Cooldown", translated: "コンプレッサー", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Duration Extender", translated: "エクステンダー", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Improved Spirit", translated: "グレータースピリット", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Mystic Slow", translated: "ミスティックスロウ", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Mystic Vulnerability", translated: "ヴァルネラビリティ", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Quicksilver Reload", translated: "クイックシルバーリロード", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Slowing Hex", translated: "スロウヘックス", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Spirit Sap", translated: "スピリットドレイン", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Suppressor", translated: "サプレッサー", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Decay", translated: "ディケイ", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Disarming Hex", translated: "ディスアームヘックス", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Greater Expansion", translated: "グレーターエクスパンダー", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Knockdown", translated: "ノックダウン", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Radiant Regeneration", translated: "ラディアントリジェネ", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Rapid Recharge", translated: "ラピッドリチャージ", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Silence Wave", translated: "サイレンスウェーブ", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Spirit Snatch", translated: "スピリットスナッチ", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Superior Cooldown", translated: "クールダウンブースト", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Superior Duration", translated: "スーパーエクステンダー", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Surge of Power", translated: "パワーサージ", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Tankbuster", translated: "タンクバスター", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Torment Pulse", translated: "トーメントパルス", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Arctic Blast", translated: "アークティックブラスト", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Boundless Spirit", translated: "バウンドレススピリット", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Cursed Relic", translated: "呪いの遺物", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Echo Shard", translated: "エコーシャード", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Escalating Exposure", translated: "エクスポージャー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Ethereal Shift", translated: "エーテリアルシフト", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Focus Lens", translated: "フォーカスレンズ", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Lightning Scroll", translated: "ライトニングスクロール", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Magic Carpet", translated: "マジックカーペット", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Mercurial Magnum", translated: "マーキュリーマグナム", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Mystic Reverb", translated: "ミスティックリバーブ", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Refresher", translated: "リフレッシャー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Scourge", translated: "スカージ", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Spirit Burn", translated: "スピリットバーン", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Transcendent Cooldown", translated: "トランセンデント", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Vortex Web", translated: "ボルテックスウェブ", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Frostbite Charm", translated: "凍傷のチャーム", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Mystic Conduit", translated: "ミスティックコンジット", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Mystical Piano", translated: "ミスティカルピアノ", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Omnicharge Signet", translated: "オムニチャージ", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Prism Blast", translated: "プリズムブラスト", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Shrink Ray", translated: "シュリンクレイ", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Unstable Concoction", translated: "不安定な調合薬", image: "", price: "Legendary", duration: "", effects: [], description: "" }
    ]
  }
};
