const wikiData = {
  heroes: [
    { original: "Abrams", translated: "エイブラムス", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Apollo", translated: "アポロ", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Bebop", translated: "ビバップ", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Billy", translated: "ビリー", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Calico", translated: "キャリコ", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Celeste", translated: "セレステ", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Dynamo", translated: "ダイナモ", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Doorman", translated: "ドアマン", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Drifter", translated: "ドリフター", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Grey Talon", translated: "グレイタロン", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Graves", translated: "グレイブス", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Haze", translated: "ヘイズ", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Holiday", translated: "ホリデイ", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Infernus", translated: "インファーナス", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Ivy", translated: "アイビー", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Kelvin", translated: "ケルビン", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Lady Geist", translated: "レディガイスト", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Lash", translated: "ラッシュ", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "McGinnis", translated: "マクギニス", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Mina", translated: "ミナ", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Mirage", translated: "ミラージュ", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Mo & Krill", translated: "モー＆クリル", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Page", translated: "ペイジ", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Paradox", translated: "パラドックス", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Pocket", translated: "ポケット", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Rem", translated: "レム", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Seven", translated: "セブン", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Shiv", translated: "シヴ", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Silver", translated: "シルバー", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Sinclair", translated: "シンクレア", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Venator", translated: "ヴェナトル", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Victor", translated: "ビクター", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Vindicta", translated: "ヴィンディクタ", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Viper", translated: "ヴァイパー", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Viscous", translated: "ヴィスカス", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Warden", translated: "ウォーデン", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Wraith", translated: "レイス", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] },
    { original: "Yamato", translated: "ヤマト", image: "", description: "", abilities: [{name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}, {name: "", desc: ""}] }
  ],
  items: {
    weapon: [
      { original: "Close Quarters", translated: "クローズクォーター", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Basic Magazine", translated: "基礎拡張マガジン", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Headshot Booster", translated: "ヘッドショットブースター", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "High-Velocity Rounds", translated: "ハイスピードラウンド", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Monster Rounds", translated: "モンスターラウンド", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Rapid Rounds", translated: "ラピッドラウンド", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Restorative Shot", translated: "ヒーリングショット", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Active Reload", translated: "アクティブリロード", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Fleetfoot", translated: "フリートフット", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Intensifying Magazine", translated: "連射強化マガジン", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Kinetic Dash", translated: "キネティックダッシュ", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Long Range", translated: "ロングレンジ", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Melee Charge", translated: "メレーチャージ", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Mystic Shot", translated: "ミスティックショット", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Opening Rounds", translated: "オープニングラウンド", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Recharging Rush", translated: "リチャージラッシュ", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Slowing Bullets", translated: "スロウバレット", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Spirit Shredder", translated: "スピリットシュレッダー", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Split Shot", translated: "スプリットショット", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Stalker", translated: "ストーカー", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Swift Striker", translated: "スイフトストライカー", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Titanic Magazine", translated: "巨大拡張マガジン", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Weakening Headshot", translated: "イグゾーストヘッドショット", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Alchemical Fire", translated: "アルケミカルファイア", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Ballistic Enchantment", translated: "バリスティックエンチャント", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Berserker", translated: "バーサーカー", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Blood Tribute", translated: "ブラッドトリビュート", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Burst Fire", translated: "バーストファイア", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Sacrifice", translated: "サクリファイス", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Escalating Resilience", translated: "エスカレートレジリエンス", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Express Shot", translated: "エクスプレスショット", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Headhunter", translated: "ヘッドハンター", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Heroic Aura", translated: "ヒロイックオーラ", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Hollow Point", translated: "ホロウポイント", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Hunter's Aura", translated: "ハンターオーラ", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Point Blank", translated: "ポイントブランク", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Sharpshooter", translated: "シャープシューター", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Spirit Rend", translated: "スピリットキラー", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Tesla Bullets", translated: "テスラバレット", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Toxic Bullets", translated: "トキシックバレット", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Weighted Shots", translated: "ヘヴィショット", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Armor Piercing Rounds", translated: "アーマーピアッサー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Capacitor", translated: "コンデンサー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Crippling Headshot", translated: "クリップリングショット", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Crushing Fists", translated: "クラッシュフィスト", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Frenzy", translated: "フレンジー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Glass Cannon", translated: "グラスキャノン", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Lucky Shot", translated: "ラッキーショット", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Ricochet", translated: "リコシェ", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Shadow Weave", translated: "シャドウウィーブ", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Silencer", translated: "サイレンサー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Spellslinger", translated: "スペルスリンガー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Spiritual Overflow", translated: "スピリットオーバーフロー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Haunting Shot", translated: "ホーンテッドショット", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Infinite Rounds", translated: "インフィニットラウンド", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Runed Gauntlets", translated: "ルーンガントレット", image: "", price: "Legendary", duration: "", effects: [], description: "" }
    ],
    vitality: [
      { original: "Extra Health", translated: "エクストラヘルス", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Extra Regen", translated: "エクストラリジェネ", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Extra Stamina", translated: "エクストラスタミナ", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Healing Rite", translated: "ヒーリングリチュアル", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Melee Lifesteal", translated: "メレーライフスティール", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Rebuttal", translated: "プロテスト", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Sprint Boots", translated: "スプリントブーツ", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Battle Vest", translated: "バトルベスト", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Bullet Lifesteal", translated: "バレットライフスティール", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Debuff Reducer", translated: "デバフリデューサー", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Enchanter's Emblem", translated: "妖術師の紋章", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Enduring Speed", translated: "ウィングブーツ", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Guardian Ward", translated: "ガーディアンワード", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Healbane", translated: "ヒールベイン", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Healing Booster", translated: "ヒーリングブースター", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Reactive Barrier", translated: "リアクティブバリア", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Restorative Locket", translated: "ヒーリングロケット", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Return Fire", translated: "リターンファイア", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Spirit Lifesteal", translated: "スピリットライフスティール", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Spirit Shielding", translated: "スピリットシールド", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Weapon Shielding", translated: "ウェポンシールド", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Bullet Resilience", translated: "バレットレジリエンス", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Counterspell", translated: "カウンタースペル", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Dispel Magic", translated: "ディスペルマジック", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Fortitude", translated: "フォルティチュード", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Fury Trance", translated: "フューリートランス", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Healing Nova", translated: "ヒーリングノヴァ", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Lifestrike", translated: "ライフストライク", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Majestic Leap", translated: "マジェスティックリープ", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Metal Skin", translated: "メタルスキン", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Rescue Beam", translated: "レスキュービーム", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Spirit Resilience", translated: "スピリットレジリエンス", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Stamina Mastery", translated: "スタミナマスタリー", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Trophy Collector", translated: "トロフィーコレクター", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Veil Walker", translated: "ベールウォーカー", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Warp Stone", translated: "ワープストーン", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Cheat Death", translated: "デスチーター", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Colossus", translated: "コロッサス", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Divine Barrier", translated: "ディバインバリア", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Diviner's Kevlar", translated: "ディバイナーズケブラー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Healing Tempo", translated: "ヒーリングテンポ", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Infuser", translated: "インフューザー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Inhibitor", translated: "インヒビター", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Juggernaut", translated: "ジャガーノート", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Leech", translated: "ライフドレイン", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Phantom Strike", translated: "ファントムストライク", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Plated Armor", translated: "プレートアーマー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Siphon Bullets", translated: "サイフォンバレット", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Spellbreaker", translated: "スペルブレイカー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Unstoppable", translated: "アンストッパブル", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Vampiric Burst", translated: "ヴァンパイアバースト", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Witchmail", translated: "ウィッチメイル", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Celestial Blessing", translated: "天の祝福", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Cloak of Opportunity", translated: "加護のマント", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Electric Slippers", translated: "エレクトリックブーツ", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Eternal Gift", translated: "エターナルギフト", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Nullification Burst", translated: "虚無の波動", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Seraphim Wings", translated: "セラフィムウィング", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Shadow Strike", translated: "シャドウストライク", image: "", price: "Legendary", duration: "", effects: [], description: "" }
    ],
    spirit: [
      { original: "Extra Charge", translated: "エクストラチャージ", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Extra Spirit", translated: "エクストラスピリット", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Golden Goose Egg", translated: "ガチョウの黄金の卵", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Mystic Burst", translated: "ミスティックバースト", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Mystic Expansion", translated: "ミスティックエクスパンダー", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Mystic Regeneration", translated: "ミスティックリジェネ", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Rusted Barrel", translated: "コロッシブバレル", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Spirit Strike", translated: "スピリットストライク", image: "", price: 800, duration: "", effects: [], description: "" },
      { original: "Arcane Surge", translated: "アーケインサージ", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Bullet Resist Shredder", translated: "レジストシュレッダー", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Cold Front", translated: "コールドフロント", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Compress Cooldown", translated: "コンプレッサー", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Duration Extender", translated: "エクステンダー", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Improved Spirit", translated: "グレータースピリット", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Mystic Slow", translated: "ミスティックスロウ", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Mystic Vulnerability", translated: "ヴァルネラビリティ", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Quicksilver Reload", translated: "クイックシルバーリロード", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Slowing Hex", translated: "スロウヘックス", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Spirit Sap", translated: "スピリットドレイン", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Suppressor", translated: "サプレッサー", image: "", price: 1600, duration: "", effects: [], description: "" },
      { original: "Decay", translated: "ディケイ", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Disarming Hex", translated: "ディスアームヘックス", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Greater Expansion", translated: "グレーターエクスパンダー", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Knockdown", translated: "ノックダウン", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Radiant Regeneration", translated: "ラディアントリジェネ", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Rapid Recharge", translated: "ラピッドリチャージ", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Silence Wave", translated: "サイレンスウェーブ", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Spirit Snatch", translated: "スピリットスナッチ", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Superior Cooldown", translated: "クールダウンブースト", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Superior Duration", translated: "スーパーエクステンダー", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Surge of Power", translated: "パワーサージ", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Tankbuster", translated: "タンクバスター", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Torment Pulse", translated: "トーメントパルス", image: "", price: 3200, duration: "", effects: [], description: "" },
      { original: "Arctic Blast", translated: "アークティックブラスト", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Boundless Spirit", translated: "バウンドレススピリット", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Cursed Relic", translated: "呪いの遺物", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Echo Shard", translated: "エコーシャード", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Escalating Exposure", translated: "エクスポージャー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Ethereal Shift", translated: "エーテリアルシフト", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Focus Lens", translated: "フォーカスレンズ", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Lightning Scroll", translated: "ライトニングスクロール", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Magic Carpet", translated: "マジックカーペット", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Mercurial Magnum", translated: "マーキュリーマグナム", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Mystic Reverb", translated: "ミスティックリバーブ", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Refresher", translated: "リフレッシャー", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Scourge", translated: "スカージ", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Spirit Burn", translated: "スピリットバーン", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Transcendent Cooldown", translated: "トランセンデント", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Vortex Web", translated: "ボルテックスウェブ", image: "", price: 6400, duration: "", effects: [], description: "" },
      { original: "Frostbite Charm", translated: "凍傷のチャーム", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Mystic Conduit", translated: "ミスティックコンジット", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Mystical Piano", translated: "ミスティカルピアノ", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Omnicharge Signet", translated: "オムニチャージ", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Prism Blast", translated: "プリズムブラスト", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Shrink Ray", translated: "シュリンクレイ", image: "", price: "Legendary", duration: "", effects: [], description: "" },
      { original: "Unstable Concoction", translated: "不安定な調合薬", image: "", price: "Legendary", duration: "", effects: [], description: "" }
    ]
  }
};
